spring:
  data:
    mongodb:
      auto-index-creation: true
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      database: ${DB_NAME}
      uri: ${DB_URL}


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              

jwt:
 secret: ${JWT_SECRET_KEY}

domain:
   url : ${CLIENT_URL} 
 
stripe:
    apiKey:${STRIPE_API_KEY}
    paymentIntentUrl:${STRIPE_PAYMENT_INTENT_URL}
