server:
   port: 8000
spring:
  data:
    mongodb:
      auto-index-creation: true
      user: admin
      password: MazeRunner
      database: shop
      uri: mongodb://admin:MazeRunner@cluster0-shard-00-00.z67tj.mongodb.net:27017/shop?ssl=true&replicaSet=atlas-juxnik-shard-0&authSource=admin&retryWrites=true&w=majority


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              

jwt:
 secret: REPLACE_THIS_WITH_YOUR_SECRET

domain:
   url : http://localhost:3000  
 
stripe:
    apiKey: sk_test_51KgQ4PSHTuE0aIU09wKUfTg9L17K4rbdpfvaiquMLF4d2m3vRazOP5KKnHusIMn6xW0SRf3p99P3gcFq5rEGLtHj0008ErUKIZ
    paymentIntentUrl: https://api.stripe.com/v1/payment_intents/
